server:
  port: 9191
  
  servlet:
    context-path: /uaa

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://${DBA_HOSTNAME}:${DBA_PORT}/${DBA_DB_NAME}
    username: ${DBA_USERNAME}
    password: ${DBA_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
     
    
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org: 
      hibernate:
        type: trace


  sleuth:
    sampler:
      probability: 1.0    
      
      
management:
  endpoints:
    
    web:
      base-path: /manage
      exposure:
        include: "*" 