version: '3.7'

services:
  config-server:
    image: darkonion/config-server:0.0.1-SNAPSHOT

    ports:
      - "8888:8888"
    restart: always
    networks:
      - dealflowbus-inner-network    
      
      
  naming-server:
    image: darkonion/main-eureka-naming-server:0.0.1-SNAPSHOT

    ports:
      - "8761:8761"
    restart: always
    depends_on:
      - config-server
    networks:
      - dealflowbus-inner-network  
      
  api-gateway:
    image: darkonion/api-gateway:0.0.1-SNAPSHOT

    ports:
      - "8765:8765"
    restart: always
    depends_on:
      - config-server
      - naming-server
    networks:
      - dealflowbus-inner-network 
      
  auth-service:
    image: darkonion/auth-service:0.0.1-SNAPSHOT

    ports:
      - "9191:9191"
    restart: always
    depends_on:
      - config-server
      - naming-server
    networks:
      - dealflowbus-inner-network 
      
  main-reader:
    image: darkonion/database-main-reader:0.0.1-SNAPSHOT

    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - config-server
      - naming-server
    networks:
      - dealflowbus-inner-network 
      
  statistics-unit:
    image: darkonion/statistics-unit:0.0.1-SNAPSHOT

    ports:
      - "8100:8100"
    restart: always
    depends_on:
      - config-server
      - naming-server
      - main-reader
    networks:
      - dealflowbus-inner-network 
      

networks:
  dealflowbus-inner-network: