apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: database-main-reader
  name: database-main-reader
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: database-main-reader
    spec:
      containers:
        - env:
            - name: DBL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DBL_PASSWORD
                  name: database-main-reader
            - name: OAUTH_ID
              valueFrom:
                secretKeyRef:
                  key: OAUTH_ID
                  name: database-main-reader
            - name: OAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  key: OAUTH_SECRET
                  name: database-main-reader
            - name: OAUTH_SERVICE_URI
              value: http://auth-service:9191/
            - name: CLOUD_GCP_ENABLED
              value: "true"
          image: darkonion/database-main-reader:0.2.7-SNAPSHOT
          name: database-main-reader
          ports:
            - name: liveness-port
              containerPort: 8081
          readinessProbe:
            httpGet:
              path: manage/health
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              path: manage/health
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 60
      restartPolicy: Always
#---
#
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    io.kompose.service: database-main-reader
#  name: database-main-reader
#spec:
#  type: NodePort
#  ports:
#    - name: "8081"
#      port: 8081
#      targetPort: 8081
#  selector:
#    io.kompose.service: database-main-reader
#
#---
#
#apiVersion: autoscaling/v1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: database-main-reader
#  namespace: default
#spec:
#  maxReplicas: 3
#  minReplicas: 1
#  scaleTargetRef:
#    apiVersion: extensions/v1beta1
#    kind: Deployment
#    name: database-main-reader
#  targetCPUUtilizationPercentage: 70
#

