apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: statistics-unit
  name: statistics-unit
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: statistics-unit
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: statistics-unit
    spec:
      containers:
      - image: darkonion/statistics-unit:0.0.5-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: statistics-unit
        env:
          - name: DATABASE_MAIN_READER_URI
            value: http://database-main-reader
        ports:
        - name: liveness-port
          containerPort: 8100
        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 1024Mi
        readinessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60    
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: statistics-unit
  name: statistics-unit
  namespace: default
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: statistics-unit
  sessionAffinity: None
  type: NodePort