apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: statistics-unit
  name: statistics-unit
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      io.kompose.service: statistics-unit
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: statistics-unit
    spec:
      containers:
      - env:
        - name: OAUTH_ID
          valueFrom:
            secretKeyRef:
              key: OAUTH_ID
              name: database-main-reader
        - name: OAUTH_SECRET
          valueFrom:
            secretKeyRef:
              key: OAUTH_SECRET
              name: database-main-reader
        - name: OAUTH_SERVICE_URI
          value: http://auth-service:9191
        - name: DATABASE_MAIN_READER_URI
          value: http://database-main-reader
        - name: CLOUD_GCP_ENABLED
          value: "true"
        image: darkonion/statistics-unit:0.2.3-SNAPSHOT
        name: statistics-unit
        ports:
        - name: liveness-port
          containerPort: 8100
        readinessProbe:
          httpGet:
            path: manage/health
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: manage/health
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60    
      restartPolicy: Always
#---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    io.kompose.service: statistics-unit
#  name: statistics-unit
#  namespace: default
#spec:
#  type: NodePort
#  ports:
#  - name: "8100"
#    port: 8100
#    targetPort: 8100
#  selector:
#    io.kompose.service: statistics-unit
#---
#apiVersion: autoscaling/v1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: statistics-unit
#  namespace: default
#spec:
#  maxReplicas: 3
#  minReplicas: 1
#  scaleTargetRef:
#    apiVersion: extensions/v1beta1
#    kind: Deployment
#    name: statistics-unit
#  targetCPUUtilizationPercentage: 70
