apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: auth-service
  name: auth-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: auth-service
    spec:
      containers:
      - env:
        - name: DBA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DBA_PASSWORD
              name: auth-service
        - name: CLOUD_GCP_ENABLED
          value: "true"
        image: darkonion/auth-service:0.2.3-SNAPSHOT
        name: auth-service
        ports:
        - name: liveness-port
          containerPort: 9191
        readinessProbe:
          httpGet:
            path: uaa/manage/health
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: uaa/manage/health
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60    
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---

apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: auth-service
  name: auth-service
spec:
  type: NodePort
  ports:
  - name: "9191"
    port: 9191
    protocol: TCP
    targetPort: 9191
  sessionAffinity: None
  selector:
    io.kompose.service: auth-service

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-service
  namespace: default
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: auth-service
  targetCPUUtilizationPercentage: 70

