
server:
  port: 8765
  
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    database-main-reader:
      path: /**
      url: http://localhost:8081/
    oauth:
      path: /oauth/**
      url: http://localhost:9191/uaa/oauth  
      
security:
  oauth2:   
    client:
      client-id: webgui
      client-secret: ovarkills11
      access-token-uri: http://localhost:9191/oauth/token
      user-authorization-uri: http://localhost:9191/uaa/oauth/authorize
    resource:
      token-info-uri: http://localhost:9191/uaa/oauth/check_token
  
ribbon:
  ReadTimeout: 60000
