<<<<<<< HEAD
eureka:
  instance:
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
security:
  oauth2:
    resource:
=======
eureka:
  instance:
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
security:
  oauth2:
    resource:
>>>>>>> 372cbd69f476f0c2a53133bb070c2ccdebc1e936
      user-info-uri: http://auth-service/uaa/users/current