server:
  port: 8081
  
  
spring:
  datasource:
    url: jdbc:mysql://darkonion.atthost24.pl:3306/13936_dfmain?serverTimezone=UTC
    username: 13936_dfmain
    password: ovarkills11
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB
      enabled: true
      

