server:
  port: 8081
  
  
spring:
  datasource:
    url: jdbc:mysql://serwer2088490.home.pl:3306/32169580_dealflowmain?serverTimezone=UTC
    username: 32169580_dealflowmain
    password: ovarkills11
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token
    client:
      client-id: webgui
      client-secret: ovarkills11
