server:
  port: 8100
  
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000 
  
database-main-reader:
  ribbon:
    listOfServers: http://localhost:8081
    ServerListRefreshInterval: 15000