server:
  port: 8081

spring:
  application:
    name: database-main-reader

  datasource:
    url: jdbc:mysql://${DBL_HOSTNAME:localhost}:${DBL_PORT:3306}/${DBL_DB_NAME:leads}
    username: ${DBL_USERNAME:dfmainadmin}
    password: ${DBL_PASSWORD:demo}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
 
      
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB
      enabled: true
         
  sleuth:
    sampler:
      probability: 1.0  

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000  

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*" 
    
#security:
#  oauth2:
#    resource:
#      token-info-uri: http://auth-service:9191/uaa/oauth/check_token
#    client:
#      client-id: webgui
#      client-secret: ovarkills11
 


