server:
  port: 8081

spring:
  application:
    name: database-main-reader

  datasource:
    url: jdbc:mysql://${DBL_HOSTNAME:localhost}:${DBL_PORT:3306}/${DBL_DB_NAME:leads}
    username: ${DBL_USERNAME:dfmainadmin}
    password: ${DBL_PASSWORD:demo}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    
#  datasource:
#    url: jdbc:mysql://darkonion.atthost24.pl:3306/13936_dfmain?serverTimezone=UTC
#    username: 13936_dfmain
#    password: ovarkills11
#    driver-class-name: com.mysql.jdbc.Driver 
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
 
      
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB
      enabled: true
         
  sleuth:
    sampler:
      probability: 1.0  

#ribbon:
#  ConnectTimeout: 60000
#  ReadTimeout: 60000  

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
    
security:   
  oauth2:
    resource:
      token-info-uri: ${OAUTH_SERVICE_URI}/uaa/oauth/check_token
    client:
      client-id: ${OAUTH_ID}
      client-secret: ${OAUTH_SECRET}


#ogging:#  level:
#    root: debug    
