server:
  port: 8081

spring:
  application:
    name: database-main-reader
  
  cloud:
    gcp:
      trace:
        enabled: ${CLOUD_GCP_ENABLED:false}

  datasource:
    url: jdbc:mysql://${DBL_HOSTNAME:localhost}:${DBL_PORT:3306}/${DBL_DB_NAME:leads?serverTimezone=UTC&useSSL=false}
    username: ${DBL_USERNAME:root}
    password: ${DBL_PASSWORD:demopass1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
 
      
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB
      enabled: true
         
  sleuth:
    sampler:
      probability: 0.25  

#ribbon:
#  ConnectTimeout: 60000
#  ReadTimeout: 60000  

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
    
security:   
  oauth2:
    resource:
      token-info-uri: ${OAUTH_SERVICE_URI:http://localhost:9191}/uaa/oauth/check_token
    client:
      client-id: ${OAUTH_ID:webgui}
      client-secret: ${OAUTH_SECRET:demopass1234}


#logging:
#  level:
#    root: debug
    
