spring:
    cloud:
      config:
        server:
          git:
            uri: https://github.com/darkonion/DealFlowBus.git
            default-label: security
            search-paths:            - config
            username: darkonion
            password: Ovarkills11
                      
    application:      name: config-server
      security:      user:        password: ovarkills11
      
server:  port: 8888
