spring:
    cloud:
      config:
        server:
          git:
            uri: https://github.com/darkonion/DealFlowBus.git
            searchPaths: security/config*
    application:      name: config-server
      security:      user:        password: ovarkills11
      
server:  port: 8888
